version: '3'
services:
  video-processor:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - INPUT_S3_BUCKET=${INPUT_S3_BUCKET}
      - OUTPUT_S3_BUCKET=${OUTPUT_S3_BUCKET}
    volumes:
      - .:/app
